using BackEndAPI.Models.Account;
using System.Security.Claims;

namespace BackEndAPI.Models.Other
{
    public static class ClaimList
    {
        public static List<Claim> GetClaim()
        {
            List<Claim> listClaim = new List<Claim>
            {
                 new Claim("Branch_Read", "Xem DS"),
                 new Claim("Branch_Create", "Thêm mới"),
                 new Claim("Branch_Update", "Cập nhật"),
                 new Claim("Branch_Delete", "Xóa"),
                 new Claim("ExpensesOther_Read", "Xem DS"),
                 new Claim("ExpensesOther_Create", "Thêm mới"),
                 new Claim("ExpensesOther_Update", "Cập nhật"),
                 new Claim("ExpensesOther_Delete", "Xóa"),
                 new Claim("PosParameter_Update", "Cập nhật"),
                 new Claim("Surcharge_Read", "Xem DS"),
                 new Claim("Surcharge_Create", "Thêm mới"),
                 new Claim("Surcharge_Update", "Cập nhật"),
                 new Claim("Surcharge_Delete", "Xóa"),
                 new Claim("PrintTemplate_Read", "Xem DS"),
                 new Claim("PrintTemplate_Update", "Cập nhật"),
                 new Claim("PrintTemplate_Delete", "Xóa"),
                 new Claim("User_Read", "Xem DS"),
                 new Claim("User_Create", "Thêm mới"),
                 new Claim("User_Update", "Cập nhật"),
                 new Claim("User_Delete", "Xóa"),
                 new Claim("User_Export", "Xuất file"),
                 new Claim("SmsEmailTemplate_Read", "Xem DS"),
                 new Claim("SmsEmailTemplate_Update", "Cập nhật"),
                 new Claim("SmsEmailTemplate_Delete", "Xóa"),
                 new Claim("SmsEmailTemplate_SendSMS", "Gửi SMS"),
                 new Claim("SmsEmailTemplate_Create", "Thêm mới"),
                 new Claim("SmsEmailTemplate_SendEmail", "Gửi Email"),
                 new Claim("SmsEmailTemplate_SendZalo", "Gửi tin nhắn Zalo"),
                 new Claim("AuditTrail_Read", "Xem"),
                 new Claim("DashBoard_Read", "Xem"),
                 new Claim("Manufacturing_Read", "Xem DS"),
                 new Claim("Manufacturing_Create", "Thêm mới"),
                 new Claim("Manufacturing_Update", "Cập nhập"),
                 new Claim("Manufacturing_Delete", "Xóa"),
                 new Claim("Manufacturing_Export", "Xuất file"),
                 new Claim("Product_Read", "Xem DS"),
                 new Claim("Product_Create", "Thêm mới"),
                 new Claim("Product_Update", "Cập nhập"),
                 new Claim("Product_Delete", "Xóa"),
                 new Claim("Product_PurchasePrice", "Giá nhập"),
                 new Claim("Product_Cost", "Giá vốn"),
                 new Claim("Product_Import", "Import"),
                 new Claim("Product_Export", "Xuất file"),
                 new Claim("PriceBook_Read", "Xem DS"),
                 new Claim("PriceBook_Create", "Thêm mới"),
                 new Claim("PriceBook_Update", "Cập nhập"),
                 new Claim("PriceBook_Delete", "Xóa"),
                 new Claim("PriceBook_Import", "Import"),
                 new Claim("PriceBook_Export", "Xuất file"),
                 new Claim("StockTake_Read", "Xem DS"),
                 new Claim("StockTake_Create", "Thêm mới"),
                 new Claim("StockTake_Update", "Cập nhập"),
                 new Claim("StockTake_Delete", "Xóa"),
                 new Claim("StockTake_Import", "Import"),
                 new Claim("StockTake_Export", "Xuất file"),
                 new Claim("StockTake_Inventory", "Xem tồn kho"),
                 new Claim("StockTake_Clone", "Sao chép"),
                 new Claim("StockTake_Finish", "Hoàn thành"),
                 new Claim("DamageItem_Read", "Xem DS"),
                 new Claim("DamageItem_Create", "Thêm mới"),
                 new Claim("DamageItem_Update", "Cập nhập"),
                 new Claim("DamageItem_Delete", "Xóa"),
                 new Claim("DamageItem_Clone", "Sao chép"),
                 new Claim("DamageItem_Export", "Xuất file"),
                 new Claim("Customer_Read", "Xem DS"),
                 new Claim("Customer_Create", "Thêm mới"),
                 new Claim("Customer_Update", "Cập nhập"),
                 new Claim("Customer_Delete", "Xóa"),
                 new Claim("Customer_Import", "Import"),
                 new Claim("Customer_Export", "Xuất file"),
                 new Claim("Customer_ViewPhone", "Điện thoại"),
                 new Claim("Customer_UpdateGroup", "Cập nhập nhóm khách hàng"),
                 new Claim("CustomerPointAdjustment_Read", "Xem DS"),
                 new Claim("CustomerPointAdjustment_Update", "Cập nhập"),
                 new Claim("CustomerAdjustment_Read", "Xem DS"),
                 new Claim("CustomerAdjustment_Create", "Thêm mới"),
                 new Claim("CustomerAdjustment_Update", "Cập nhập"),
                 new Claim("CustomerAdjustment_Delete", "Xóa"),
                 new Claim("SupplierAdjustment_Read", "Xem DS"),
                 new Claim("SupplierAdjustment_Create", "Thêm mới"),
                 new Claim("SupplierAdjustment_Update", "Cập nhập"),
                 new Claim("SupplierAdjustment_Delete", "Xóa"),
                 new Claim("DeliveryAdjustment_Read", "Xem DS"),
                 new Claim("DeliveryAdjustment_Create", "Thêm mới"),
                 new Claim("DeliveryAdjustment_Update", "Cập nhập"),
                 new Claim("DeliveryAdjustment_Delete", "Xóa"),
                 new Claim("Supplier_Read", "Xem DS"),
                 new Claim("Supplier_Create", "Thêm mới"),
                 new Claim("Supplier_Update", "Cập nhập"),
                 new Claim("Supplier_Delete", "Xóa"),
                 new Claim("Supplier_Import", "Import"),
                 new Claim("Supplier_Export", "Xuất file"),
                 new Claim("Supplier_ViewPhone", "Điện thoại"),
                 new Claim("Supplier_UpdateGroup", "Cập nhập nhóm NCC"),
                 new Claim("PartnerDelivery_Read", "Xem DS"),
                 new Claim("PartnerDelivery_Create", "Thêm mới"),
                 new Claim("PartnerDelivery_Update", "Cập nhập"),
                 new Claim("PartnerDelivery_Delete", "Xóa"),
                 new Claim("PartnerDelivery_Import", "Import"),
                 new Claim("PartnerDelivery_Export", "Xuất file"),
                 new Claim("PurchasePayment_Read", "Xem DS"),
                 new Claim("PurchasePayment_Create", "Thêm mới"),
                 new Claim("PurchasePayment_Update", "Cập nhập"),
                 new Claim("Payment_Read", "Xem DS"),
                 new Claim("Payment_Create", "Thêm mới"),
                 new Claim("Payment_Update", "Cập nhập"),
                 new Claim("FinancialReport_SalePerformanceReport", "KQ HĐ Kinh Doanh"),
                 new Claim("UserReport_ByProfitReport", "Lợi nhuận"),
                 new Claim("UserReport_ByUserReport", "Hàng bán theo NV"),
                 new Claim("UserReport_BySaleReport", "Bán hàng"),
                 new Claim("SaleReport_SaleByUser", "Nhân viên"),
                 new Claim("SaleReport_SaleProfitByInvoice", "Lợi nhuận"),
                 new Claim("SaleReport_SaleDiscountByInvoice", "Giảm giá hóa đơn"),
                 new Claim("SaleReport_SaleByRefund", "Trả hàng"),
                 new Claim("SaleReport_SaleByTime", "Thời gian"),
                 new Claim("SaleReport_BranchSaleReport", "Chi nhánh"),
                 new Claim("OrderReport_ByDocReport", "Giao dịch"),
                 new Claim("OrderReport_ByProductReport", "Hàng hóa"),
                 new Claim("EndOfDayReport_EndOfDaySynthetic", "Tổng hợp"),
                 new Claim("EndOfDayReport_EndOfDayProduct", "Hàng hóa"),
                 new Claim("EndOfDayReport_EndOfDayCashFlow", "Thu chi"),
                 new Claim("EndOfDayReport_EndOfDayDocument", "Bán hàng"),
                 new Claim("SupplierReport_BigByLiabilitiesReport", "Công nợ"),
                 new Claim("SupplierReport_SupplierInforReport", "Hàng nhập theo NCC"),
                 new Claim("SupplierReport_PurchaseOrderReport", "Nhập hàng"),
                 new Claim("SaleChannelReport_ByProduct", "Hàng bán theo kênh"),
                 new Claim("SaleChannelReport_ByProfit", "Lợi nhuận"),
                 new Claim("SaleChannelReport_BySale", "Bán hàng"),
                 new Claim("ProductReport_ProducStockInOutStock", "Giá trị kho"),
                 new Claim("ProductReport_ProductByBatchExpire", "Hạn sử dụng"),
                 new Claim("ProductReport_ProductByCustomer", "Khách theo bán hàng"),
                 new Claim("ProductReport_ProductByDamageItem", "Xuất hủy"),
                 new Claim("ProductReport_ProductBySupplier", "NCC theo hàng nhập"),
                 new Claim("ProductReport_ProductByUser", "Nhân viên theo hàng bán"),
                 new Claim("ProductReport_ProducInOutStock", "Xuất nhập tồn"),
                 new Claim("ProductReport_ProducInOutStockDetail", "Xuất nhập tồn chi tiết"),
                 new Claim("ProductReport_ProductByProfit", "Lợi nhuận"),
                 new Claim("ProductReport_ProductBySale", "Bán hàng"),
                 new Claim("CustomerReport_BigCustomerDebt", "Công nợ"),
                 new Claim("CustomerReport_CustomerProduct", "Hàng bán theo khách"),
                 new Claim("CustomerReport_CustomerSale", "Bán hàng"),
                 new Claim("CustomerReport_CustomerProfit", "Lợi nhuận"),
                 new Claim("BankAccount_Create", "Xem DS"),
                 new Claim("BankAccount_Delete", "Xóa"),
                 new Claim("BankAccount_Update", "Cập nhập"),
                 new Claim("CashFlow_Read", "Xem DS"),
                 new Claim("CashFlow_Create", "Thêm mới"),
                 new Claim("CashFlow_Update", "Cập nhập"),
                 new Claim("CashFlow_Delete", "Xóa"),
                 new Claim("CashFlow_Export", "Xuất file"),
                 new Claim("Campaign_Read", "Xem DS"),
                 new Claim("Campaign_Create", "Thêm mới"),
                 new Claim("Campaign_Update", "Cập nhập"),
                 new Claim("Campaign_Delete", "Xóa"),
                 new Claim("VoucherCampaign_Read", "Xem DS"),
                 new Claim("VoucherCampaign_Create", "Thêm mới"),
                 new Claim("VoucherCampaign_Update", "Cập nhập"),
                 new Claim("VoucherCampaign_Delete", "Xóa"),
                 new Claim("VoucherCampaign_Release", "Phát hành"),
                 new Claim("EmployeeLimit_Read", "Xem DS"),
                 new Claim("CouponCampaign_Read", "Xem DS"),
                 new Claim("CouponCampaign_Create", "Thêm mới"),
                 new Claim("CouponCampaign_Update", "Cập nhập"),
                 new Claim("CouponCampaign_Delete", "Xóa"),

                 new Claim("System", "Hệ thống"),
                 new Claim("Item", "Hàng hóa"),
                 new Claim("Transaction", "Giao dịch"),
                 new Claim("BusinessPartner", "Đối tác"),
                 new Claim("Report", "Báo cáo"),
                 new Claim("Cash", "Sổ quỹ"),
                 new Claim("Promotion", "Khuyến mại"),
                 new Claim("Voucher", "Voucher"),
                 new Claim("Employee", "Nhân viên"),
                 new Claim("Coupon", "Coupon"),
                 new Claim("ExpensesOther", "Chi phí nhập hàng"),
                 new Claim("PosParameter", "Thiết lập"),
                 new Claim("Surcharge", "Thu khác"),
                 new Claim("PrintTemplate", "Mẫu in"),
                 new Claim("User", "Người dùng"),
                 new Claim("SmsEmailTemplate", "SMS / Email"),
                 new Claim("AuditTrail", "Lịch sử thao tác"),
                 new Claim("DashBoard", "Tổng quan"),
            };
            return listClaim;
        }
       
    }
}
